// flow-typed signature: 4ebaaaceef54a22211b47b4dd90d8fd4
// flow-typed version: <<STUB>>/@core/reducers_v1.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@core/reducers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@core/reducers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@core/reducers/menu/actions' {
  declare module.exports: any;
}

declare module '@core/reducers/menu/constants' {
  declare module.exports: any;
}

declare module '@core/reducers/menu' {
  declare module.exports: any;
}

declare module '@core/reducers/menu/initialState' {
  declare module.exports: any;
}

declare module '@core/reducers/prompter/actions' {
  declare module.exports: any;
}

declare module '@core/reducers/prompter' {
  declare module.exports: any;
}

declare module '@core/reducers/prompter/initialState' {
  declare module.exports: any;
}

// Filename aliases
declare module '@core/reducers/index' {
  declare module.exports: $Exports<'@core/reducers'>;
}
declare module '@core/reducers/index.js' {
  declare module.exports: $Exports<'@core/reducers'>;
}
declare module '@core/reducers/menu/actions.js' {
  declare module.exports: $Exports<'@core/reducers/menu/actions'>;
}
declare module '@core/reducers/menu/constants.js' {
  declare module.exports: $Exports<'@core/reducers/menu/constants'>;
}
declare module '@core/reducers/menu/index' {
  declare module.exports: $Exports<'@core/reducers/menu'>;
}
declare module '@core/reducers/menu/index.js' {
  declare module.exports: $Exports<'@core/reducers/menu'>;
}
declare module '@core/reducers/menu/initialState.js' {
  declare module.exports: $Exports<'@core/reducers/menu/initialState'>;
}
declare module '@core/reducers/prompter/actions.js' {
  declare module.exports: $Exports<'@core/reducers/prompter/actions'>;
}
declare module '@core/reducers/prompter/index' {
  declare module.exports: $Exports<'@core/reducers/prompter'>;
}
declare module '@core/reducers/prompter/index.js' {
  declare module.exports: $Exports<'@core/reducers/prompter'>;
}
declare module '@core/reducers/prompter/initialState.js' {
  declare module.exports: $Exports<'@core/reducers/prompter/initialState'>;
}
