// flow-typed signature: 29a34cd72e81893c886b5ec725680d1b
// flow-typed version: <<STUB>>/@pkgs/root-dom-tag_v1.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pkgs/root-dom-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pkgs/root-dom-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pkgs/root-dom-tag/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pkgs/root-dom-tag/index' {
  declare module.exports: $Exports<'@pkgs/root-dom-tag'>;
}
declare module '@pkgs/root-dom-tag/index.js' {
  declare module.exports: $Exports<'@pkgs/root-dom-tag'>;
}
declare module '@pkgs/root-dom-tag/index.spec.js' {
  declare module.exports: $Exports<'@pkgs/root-dom-tag/index.spec'>;
}
