// flow-typed signature: 147121b075b824aa48dbda762af9234d
// flow-typed version: <<STUB>>/@views/header_v1.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@views/header'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@views/header' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@views/header/MenuButton' {
  declare module.exports: any;
}

// Filename aliases
declare module '@views/header/index' {
  declare module.exports: $Exports<'@views/header'>;
}
declare module '@views/header/index.js' {
  declare module.exports: $Exports<'@views/header'>;
}
declare module '@views/header/MenuButton.js' {
  declare module.exports: $Exports<'@views/header/MenuButton'>;
}
