// flow-typed signature: 52dc6346b5f6f8bb7cefcb2cc4a72bde
// flow-typed version: <<STUB>>/@views/main_v1.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@views/main'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@views/main' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@views/main/index' {
  declare module.exports: $Exports<'@views/main'>;
}
declare module '@views/main/index.js' {
  declare module.exports: $Exports<'@views/main'>;
}
