// flow-typed signature: d1edb2022a1723852b35e3336971de3e
// flow-typed version: <<STUB>>/@views/menu_v1.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@views/menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@views/menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@views/menu/Background' {
  declare module.exports: any;
}

declare module '@views/menu/MenuList' {
  declare module.exports: any;
}

// Filename aliases
declare module '@views/menu/Background.js' {
  declare module.exports: $Exports<'@views/menu/Background'>;
}
declare module '@views/menu/index' {
  declare module.exports: $Exports<'@views/menu'>;
}
declare module '@views/menu/index.js' {
  declare module.exports: $Exports<'@views/menu'>;
}
declare module '@views/menu/MenuList/index' {
  declare module.exports: $Exports<'@views/menu/MenuList'>;
}
declare module '@views/menu/MenuList/index.js' {
  declare module.exports: $Exports<'@views/menu/MenuList'>;
}
